In [1]:
import pandas as pd
import pickle 
import numpy as np

In [2]:
modelList = ["288_96", "192_192", "384_0", "justEn"]

print("rows = epoch, columns=fold")
for modelSuffix in modelList: 
    print("MODEL: " + str(modelSuffix))
    inPath = "/home/blitt/projects/localNews/models/sentEmbeddings/2.0-biModelAblation/" + modelSuffix
    with open(inPath + "/outputData.pkl", "rb") as f: 
        corrList = pickle.load(f)

    with open(inPath + "/time.pkl", "rb") as f: 
        time = pickle.load(f)
    
    print("RUNNING TIME: ")
    print(time)
    
    corrMat = np.array(corrList).T
    
    print(corrMat)
    print("\n")
    """
    EPOCHS = 3
    FOLDS = 5

    iterList = []
    corrList = []
    #go through each epoch 
    for epoch in range(EPOCHS): 
        corrList = []
        for fold in range(FOLDS):

            df = pd.DataFrame(metrics[fold][epoch]).T
            df.columns =  ["loss", "pred", "true"]
            corr = np.corrcoef(df["pred"], df["true"])[1,0]
            corrList.append(corr)
        print("Epoch: " + str(epoch))
        print(corrList)
        print("Standard Deviation: " + str(np.std(corrList)))
        print("Average Correlation: " + str(np.mean(corrList)))
        print("---------------------")
    print("\n\n")
    """

rows = epoch, columns=fold
MODEL: 288_96
RUNNING TIME: 
2285.389204978943
[[0.8303091  0.85232384 0.86591196 0.87114802 0.85830033]
 [0.85381365 0.88883661 0.89279378 0.8973561  0.88566837]
 [0.85555911 0.89038076 0.89541454 0.89773812 0.88626717]]


MODEL: 192_192
RUNNING TIME: 
6102.597308397293
[[0.88000046 0.88173918 0.88939577 0.88401655 0.89387063]]


MODEL: 384_0
RUNNING TIME: 
2467.7342183589935
[[0.85701712 0.85654793 0.84651046 0.87678753 0.85087732]
 [0.88518885 0.88358779 0.87121641 0.89593042 0.88408045]
 [0.88610724 0.88396739 0.87324103 0.89654942 0.88600845]]


MODEL: justEn
RUNNING TIME: 
1409.3784627914429
[[0.87643742 0.85353291 0.84655162 0.86896564 0.84664829]
 [0.90207286 0.87024556 0.87346538 0.89576742 0.87236564]
 [0.90361238 0.87147904 0.87518601 0.89658728 0.87418146]]




In [17]:
corrMat.T

array([[0.87643742, 0.85353291, 0.84655162, 0.86896564, 0.84664829],
       [0.90207286, 0.87024556, 0.87346538, 0.89576742, 0.87236564],
       [0.90361238, 0.87147904, 0.87518601, 0.89658728, 0.87418146]])